main: net.initialposition.globalcountdown.GlobalCountdown
name: GlobalCountdown
version: 1.3.0
description: Shows every user a countdown. When the countdown expires, all users get set to spectator mode.
api-version: 1.16
author: InitialPosition
website: www.initialposition.net